### ISSUE TITLE
[M-2] Pricing module is not verified when creating exchanges

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#239]
When creating an exchange in the `BiPoolManager` contract, the pricing module is specified as an input parameter in the `PoolExchange _exchange` struct. However, there are no validations that the address of the pricing module corresponds to a canonical version of this module. This can cause, for example, the previous version of the constant sum module to be used in the exchange creation and, therefore, to calculate swap amounts incorrectly. The only check performed during swaps is in the `pricingModuleIdentifier`:

```solidity
function pricingModuleIdentifier(PoolExchange memory exchange) internal view returns (bytes32) {
  return keccak256(abi.encodePacked(exchange.pricingModule.name()));
} 
```

This also opens up other scenarios where invalid pricing module addresses can be used.

**Remediations to Consider**

Keeping in the `BiPoolManager` contract’s storage the address of the latest or allowed pricing modules and asserting it’s used in `createExchange`.

**Acceptance Criteria**

- [x] BiPoolManager includes a mapping of pricing module identifiers to addresses
- [x] Pricing module is validated on exchange creation

**Comment by bayological** [comment]
As a result of this issue, it's possible for an already-created exchange to reference an older version of a pricing module only if the exchange is not recreated as part of the governance update. The chances of this happening are low. However, we should consider storing the pricing module identifier in the poolExchane struct instead of the actual module address, and then reading this from the newly added mapping. The downside of this is we increase the gas cost of swaps by adding additional storage reads. The result of this would be we no longer need to recreate exchanges when pricing modules are updated.
