### ISSUE TITLE
Gas comparison between McMint swaps and Mento V1 swaps

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#33]
### Description

Historically gas hasn't been that big of a concern for Celo contract development, but as we're looking more towards being cross-chain we need to start thinking about this critically. Therefore, at a minimum, we need to start understanding the delta in gas we're introducing with new features by comparing gas usage in Mento V1 swaps with gas usage in McMint. 

### Acceptance criteria

- Come up with a few swap scenarios
- Add tests that do swaps through the legacy Exchange contract and through the Broker contract in those scenarios
- (research) Have a form of gas report saved in the repo and integrated with CI

**Comment by tobikuhlmann** [comment]
Ran into some comparison problems and conflicting results: Test setups and Mock contracts are different for V1 (Exchange) and V2 (McMint Broker). I decided to wait for the McMint Baklava deployment https://github.com/mento-protocol/mento-core/issues/28 to be finished, and compare both versions in production to get real gas-estimates. Otherwise a lot of my test setups would be double work

**Comment by tobikuhlmann** [comment]
PR to review: https://github.com/mento-protocol/mento-core/pull/76
